{% set version = "1.35.1" %}

package:
  name: nanoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanoplot/NanoPlot-{{ version }}.tar.gz
  sha256: e55066c007dd065460cc2de4d3728f81fffb4e1050f18eecadf78e88bdf93211

build:
  entry_points:
    - NanoPlot=nanoplot.NanoPlot:main
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - biopython
    - pysam >0.10.0.0
    - pandas >=0.22.0
    - numpy
    - scipy
    - python-dateutil
    - nanoget >=1.14.0
    - nanomath >=1.0.0
    - plotly >=4.9.0
    - pyarrow
    - python-kaleido

test:
  imports:
    - nanoplot
  commands:
    - NanoPlot --help

about:
  home: https://github.com/wdecoster/NanoPlot
  license: GPL-3.0-only
  summary: 'Plotting suite for long read sequencing data and alignments'
  license_family: GPL
