{% set version = "0.4.16" %}
{% set github = "https://github.com/hbc/bcbioSingleCell" %}

package:
  name: r-bcbiosinglecell
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 02cdf80087b97066fc93d367fc166cd7795d027b913c6278d7c83e4ee1a42414

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
      # Depends:
    - r-base
    - bioconductor-singlecellexperiment >=1.10.1
    - r-basejump >=0.13.1
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidgenerics >=0.4
    - r-acidplots >=0.3
    - r-bcbiobase >=0.6.15
    - r-cli >=2.0
    - r-ggplot2 >=3.2
    - r-ggridges >=0.5
    - r-goalie >=0.4.8
    - r-rlang >=0.4
    - r-stringr >=1.4
      # Suggests:
    - bioconductor-biocstyle >=2.14
    - r-knitr >=1.27
    - r-r.utils >=2.9
    - r-rmarkdown >=2.0
    - r-sessioninfo >=1.1
    - r-tidyverse >=1.3
  run:
      # Depends:
    - r-base
    - bioconductor-singlecellexperiment >=1.10.1
    - r-basejump >=0.13.1
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidgenerics >=0.4
    - r-acidplots >=0.3
    - r-bcbiobase >=0.6.15
    - r-cli >=2.0
    - r-ggplot2 >=3.2
    - r-ggridges >=0.5
    - r-goalie >=0.4.8
    - r-rlang >=0.4
    - r-stringr >=1.4
      # Suggests:
    - bioconductor-biocstyle >=2.14
    - r-knitr >=1.27
    - r-r.utils >=2.9
    - r-rmarkdown >=2.0
    - r-sessioninfo >=1.1
    - r-tidyverse >=1.3

test:
  commands:
    - $R -e "library('bcbioSingleCell')"

about:
  home: https://bioinformatics.sph.harvard.edu/bcbioSingleCell/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: R package for bcbio single-cell RNA-seq analysis.

extra:
  recipe-maintainers:
    - mjsteinbaugh
