{% set version = "4.2.1" %}

package:
  name: shapeit4
  version: {{ version }}

source:
  url: https://github.com/odelaneau/shapeit4/archive/v{{ version }}.tar.gz
  sha256: 9f0680d4d42f9c206dea3583553a5ca68bd6bbcdfe40e4e8ac2587f5050bac63

build:
  skip: True  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - bzip2
    - htslib
  run:
    - boost-cpp
    - bzip2
    - htslib

test:
  commands:
    - shapeit4 --help

about:
  home: https://odelaneau.github.io/shapeit4/
  license: MIT
  license_file: LICENSE
  summary: fast and accurate method for estimation of haplotypes (phasing)

extra:
  identifiers:
    - doi:10.1101/493403
