{% set name = "ultraplex" %}
{% set version = "1.2.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d31ad7a659371d546c200290332172bbad917f3fded167d3ea92e785824ce519


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py < 37 or py > 39]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - setuptools_scm
  run:
    - python
    - xopen >=1.0.0
    - dnaio >=0.5.0
    - pigz

test:
  imports:
    - ultraplex
  commands:
    - ultraplex --help

about:
  home: "https://github.com/ulelab/ultraplex.git"
  license: MIT
  license_family: MIT
  summary: "fastq demultiplexer"

extra:
  recipe-maintainers:
    - Delayed-Gitification
