{% set version = "1.1.3" %}
{% set sha256 = "a1df3251d6b1a51452d8e28681864b014d5889e159a25486775e481adde1338e" %}

package:
  name: radsex
  version: {{ version }} 

build:
  number: 0
  skip: true  # [osx]

source:
  url: https://github.com/SexGenomicsToolkit/radsex/archive/{{ version }}.tar.gz 
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib

test:
  commands:
    - radsex --help

about:
  home: https://sexgenomicstoolkit.github.io/html/radsex/introduction.html
  license: GPL3
  license_file: LICENSE
  summary: The radsex software is part of RADSex, a computational workflow for the analysis of sex-determination using RAD-Sequencing data.
